model:
  name: 'osnet_x1_0_mil'
  pretrained: True

data:
  type: 'image'
  root: '/home/jtyo/data'
  sources: ['sysu30k']
  targets: ['sysu30k']
  height: 256
  width: 128
  combineall: False
  transforms: ['random_flip']
  save_dir: 'log/sysu30k'
  workers: 4

sampler:
  train_sampler: 'RandomBagSampler'

train:
  optim: 'amsgrad'
  lr: 0.0005
  max_epoch: 5
  batch_size: 10
  fixbase_epoch: 1
  open_layers: ['classifier', 'bag_classifier', 'attention', 'fc']
  lr_scheduler: 'one_cycle'
  bag_size: 20

test:
  batch_size: 300
  dist_metric: 'euclidean'
  normalize_feature: False
  evaluate: False
  eval_freq: 1
  rerank: False

loss:
  name: 'triplet'
  triplet:
    weight_t: 0.0
    weight_x: 1.0
    weight_d: 0.0
    margin: 1.0
